[package]
name = "perfect-reconstructibility-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = "1.3.2"
libfuzzer-sys = "0.4.7"

[dependencies.perfect-reconstructibility]
path = ".."
